name: Test

on:
  push:
    branches:
      - main

jobs:
  RunPython:
    name: VladaLearn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: python3 example_game.py